#include <cstdio>
#include <cstdint>
#include <deque>

#include "verilated.h"
#include "Vmont_reduce.h"    // generated by Verilator
#include "ref_model.hpp"

// clock helper
static void tick(Vmont_reduce* dut) {
    dut->clk = 0; dut->eval();
    dut->clk = 1; dut->eval();
}

// reset helper
static void reset(Vmont_reduce* dut) {
    dut->rst_n = 0;
    dut->in_valid = 0;
    dut->x = 0;
    for (int i = 0; i < 4; i++) tick(dut);
    dut->rst_n = 1;
}

int main(int argc, char** argv) {
    Verilated::commandArgs(argc, argv);

    // TODO: check_constants() first

    auto* dut = new Vmont_reduce;
    reset(dut);

    const uint32_t N = 1u << 24;
    std::deque<uint32_t> inflight;
    long mismatches = 0;
    long checked = 0;

    // TODO: feed loop
    // TODO: drain remaining outputs after feeding stops
    // TODO: report result

    delete dut;
    return mismatches ? 1 : 0;
}